### ISSUE TITLE
When is Linux support going to be ready?

### ISSUE THREAD

**Issue by mikelpint** [davidferguson/pibakery#119] opened 2017-11-01 20:48 UTC

**Comment by PeterChauYEG** [comment] 2017-12-28 20:11
Hi,

I was able to install PiBakery by following the install from [source instructions](https://github.com/davidferguson/pibakery/). I had issues with node and was able to fix that by using `nvm` to install `node 9.0.3`. Don't forget setup your os'.

**Comment by mikelpint** [comment] 2017-12-29 00:01
OK, thank you.

**Comment by pintman** [comment] 2018-03-25 10:31
This seems to be duplicate of #110.

**Comment by davidferguson** [comment] 2018-08-31 14:32
Closing as duplicate of #110

**Closed by davidferguson** 2018-08-31 14:32 UTC
