### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by mawg** [davidferguson/pibakery#163] opened 2018-08-27 12:00 UTC
![delete me](https://user-images.githubusercontent.com/2999044/44658515-04f64780-a9f9-11e8-82ad-98aeb9ba1fc3.png)

**Comment by davidferguson** [comment] 2018-08-28 15:19
Can you confirm that you're using PiBakery v2 and on Windows 10? Assuming both are true, this is a duplicate of #157.

**Closed by davidferguson** 2018-08-28 15:19 UTC
